AWSTemplateFormatVersion: 2010-09-09

# オートスケーリング、起動テンプレートに関する項目を記載

Resources: 
  LaunchTemplateWeb01:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: LaunchTemplateWeb01
      LaunchTemplateData: 
        DisableApiTermination: true
        ImageId: ami-03a9b50718282f444
        InstanceType: t2.micro
        IamInstanceProfile:
          Arn: !Sub "arn:aws:iam::${AWS::AccountId}:instance-profile/ecsInstanceRole"
        KeyName: MyKeyPair
        SecurityGroupIds:
          - !ImportValue SecurityGroupWeb
        UserData: 
          !Base64 |
            #!bin/bash
            echo ECS_CLUSTER=WebServerCluster >> /etc/ecs/ecs.config
        TagSpecifications:
          - ResourceType: instance
            Tags:
            - Key: Name
              Value: WebServer-Auto-FromCF

  AutoScalingGroup01:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: WebServerGroup
      VPCZoneIdentifier:
        - !ImportValue PublicSubnet01
        - !ImportValue PublicSubnet02
      DesiredCapacity: 1 
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplateWeb01
        Version: !GetAtt LaunchTemplateWeb01.LatestVersionNumber
      MaxSize: 2
      MinSize: 1 
      NewInstancesProtectedFromScaleIn: True
      Tags:
        - Key: Name
          Value: ASG-WebServer
          PropagateAtLaunch: True
  
Outputs:
  AutoScalingGroup01:
    Value: !Ref AutoScalingGroup01
    Export: 
      Name: AutoScalingGroup01