AWSTemplateFormatVersion: 2010-09-09

# iamに関する記載

Resources: 
  EcsServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: EcsServiceRole
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs.amazonaws.com
                - ecs-tasks.amazonaws.com
            Action:
              - "sts:AssumeRole"

  EcsServicePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: EcsServicePolicy
      Roles:
        - !Ref EcsServiceRole 
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow 
            Action:
              - "ec2:AttachNetworkInterface"
              - "ec2:CreateNetworkInterface"
              - "ec2:CreateNetworkInterfacePermission"
              - "ec2:DeleteNetworkInterface"
              - "ec2:DeleteNetworkInterfacePermission"
              - "ec2:Describe*"
              - "ec2:DetachNetworkInterface"
              - "ec2:AuthorizeSecurityGroupIngress"
              - "elasticloadbalancing:DeregisterInstancesFromLoadBalancer"
              - "elasticloadbalancing:DeregisterTargets"
              - "elasticloadbalancing:Describe*"
              - "elasticloadbalancing:RegisterInstancesWithLoadBalancer"
              - "elasticloadbalancing:RegisterTargets"
              - "route53:ChangeResourceRecordSets"
              - "route53:CreateHealthCheck"
              - "route53:DeleteHealthCheck"
              - "route53:Get*"
              - "route53:List*"
              - "route53:UpdateHealthCheck"
              - "servicediscovery:DeregisterInstance"
              - "servicediscovery:Get*"
              - "servicediscovery:List*"
              - "servicediscovery:RegisterInstance"
              - "servicediscovery:UpdateInstanceCustomHealthStatus"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource: "*"
 
  EcsTaskRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: EcsTaskRole
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
                - ecs.amazonaws.com
            Action:
              - "sts:AssumeRole"

  EcsTaskPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: EcsTaskPolicy
      Roles:
        - !Ref EcsTaskRole 
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow 
            Action:
              - "iam:Get*"
              - "ecr:GetAuthorizationToken"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:GetRepositoryPolicy"
              - "ecr:DescribeRepositories"
              - "ecr:ListImages"
              - "ecr:BatchGetImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
              - "ecr:PutImage"
              - "ecs:DescribeServices"
              - "ecs:DescribeTaskDefinition"
              - "ecs:RegisterTaskDefinition"
              - "ecs:UpdateService"
              - "ecs:RunTask"
              - "ecs:DescribeTasks"
              - "ecs:ListTasks"
              - "ecs:CreateCluster"
              - "ecs:DeregisterContainerInstance"
              - "ecs:DiscoverPollEndpoint"
              - "ecs:Poll"
              - "ecs:RegisterContainerInstance"
              - "ecs:StartTelemetrySession"
              - "ecs:UpdateContainerInstance"
              - "ecs:Submit*"
              - "iam:Get*"
              - "iam:List*"
              - "iam:PassRole"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
              - "ssm:GetParameters"
              - "secretsmanager:GetSecretValue"
              - "kms:Decrypt"
            Resource: "*"
  
  EcsTaskInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref EcsTaskRole

Outputs:
  EcsTaskRole:
    Value: !Ref EcsTaskRole
    Export:
      Name: EcsTaskRole
  
  EcsServiceRole:
    Value: !Ref EcsServiceRole
    Export:
      Name: EcsServiceRole