AWSTemplateFormatVersion: 2010-09-09

# TargetGroup
# Target
# LoadBalacer

Resources: 

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      HealthCheckEnabled: True
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckPort: 80
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 3
      Matcher: 
        HttpCode: 200
      Name: TargetGroup
      Port: 80
      Protocol: HTTP
      TargetType: instance
      UnhealthyThresholdCount: 2
      VpcId: !ImportValue MyVPC01

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      Name: LoadBalancerWeb
      Scheme: internet-facing
      SecurityGroups: 
        - !ImportValue SecurityGroupAlb
      Subnets: 
        - !ImportValue PublicSubnet01
        - !ImportValue PublicSubnet02
      Tags: 
        - Key: Name
          Value: LoadBalancerWeb
  
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      DefaultActions: 
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP

Outputs:
  LoadBalancer:
    Value: !Ref LoadBalancer
    Export:
      Name: LoadBalancer

  TargetGroup:
    Value: !Ref TargetGroup
    Export:
      Name: TargetGroup