AWSTemplateFormatVersion: 2010-09-09

Parameters:
  HitokotomonoDBPW:
    Description: HitokotomonoDB-Password
    Type: String
    Default: Password

Resources: 
  HitokotomonoSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Hitokotomono Blog Database
      DBSubnetGroupName: HitokotomonoSubnetGroup
      SubnetIds:
        - !ImportValue PrivateSubnet01
        - !ImportValue PrivateSubnet02

  HitokotomonoRDS:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 10
      DBInstanceClass: db.t2.micro
      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: true
      AvailabilityZone: !Sub ${AWS::Region}a
      DBSubnetGroupName: !Ref HitokotomonoSubnetGroup
      DBInstanceIdentifier: hitokotomono-db
      DBName: HitokotomonoDB
      VPCSecurityGroups: 
        - !ImportValue SecurityGroupDB 
      Engine: mysql
      EngineVersion: 5.7 
      MasterUsername: HitokotomonoUser
      MasterUserPassword: !Sub ${HitokotomonoDBPW}
      MultiAZ: false
      PubliclyAccessible: false
      StorageType: gp2
      VPCSecurityGroups:
        - !ImportValue SecurityGroupDB
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-db