AWSTemplateFormatVersion: 2010-09-09

# セキュリティグループ関係

Resources: 
  SecurityGroupWeb:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SG-web
      GroupDescription: SG-web
      VpcId: !ImportValue MyVPC01
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: SecurityGroupWeb-fromCF

  SecurityGroupDB:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SG-DB
      GroupDescription: SG-DB
      VpcId: !ImportValue MyVPC01
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref SecurityGroupWeb
      Tags:
        - Key: Name
          Value: SecurityGroupDB-fromCF

  SecurityGroupAlb:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SecurityGroupAlb
      GroupDescription: SG-Alb
      VpcId: !ImportValue MyVPC01
      SecurityGroupIngress:
        IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        IpProtocol: -1
        FromPort: 0 
        ToPort: 0
        CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: SecurityGroupAlb-fromCF

Outputs:
  SecurityGroupWeb:
    Value: !Ref SecurityGroupWeb
    Export:
      Name: SecurityGroupWeb

  SecurityGroupDB:
    Value: !Ref SecurityGroupDB
    Export:
      Name: SecurityGroupDB
  
  SecurityGroupAlb:
    Value: !Ref SecurityGroupAlb
    Export:
      Name: SecurityGroupAlb
